# Generated by Django 3.2.5 on 2021-07-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brewer_name', models.CharField(max_length=200)),
                ('brewer_state', models.CharField(max_length=24)),
                ('brewer_opened', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.CharField(max_length=64)),
                ('beer_type', models.CharField(max_length=64)),
                ('beer_brewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='beer_reviews_app.brewer')),
            ],
        ),
    ]
