# Generated by Django 3.2.5 on 2021-07-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_reviews_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beer_brewer',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Brewer',
        ),
    ]
